{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - port: {{ .Values.podMonitor.port }}
      path: {{ .Values.podMonitor.path }}
      interval: {{ .Values.podMonitor.interval }}
      scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
{{- end }} 