name: Build, unit/smoke test and lint branch

on: [pull_request]

jobs:
  run-e2e-tests:
    name: E2E [Electron/Node 16]
    uses: ./.github/workflows/e2e-reusable.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      user: ${{ github.event.pull_request.user.login || 'PR User' }}
      spec: 'e2e/*'
      run-env: base:16.18.1
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
