name: End-to-End tests parallel
run-name: Parallel E2E Tests ${{ inputs.branch }} - ${{ inputs.user }}

on:
  push:
    branches:
      - "parallel_e2e"
  repository_dispatch:
    types: [slack_command]
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub branch to test.'
        required: false
        default: 'parallel_e2e'
      user:
        description: 'User who kicked this off.'
        required: false
        default: 'schedule'
      spec:
        description: 'Specify specs.'
        required: false
        default: 'e2e/*'
      run-env:
        description: 'Node env version to run tests with.'
        required: false
        default: 'browsers:node16.18.0-chrome90-ff88'
      start-url:
        description: 'URL to call after workflow is kicked off.'
        required: false
        default: ''
      success-url:
        description: 'URL to call after workflow is done.'
        required: false
        default: ''

jobs:
  reusable-e2e:
    uses: n8n-io/n8n/.github/workflows/e2e-reusable.yml@parallel_e2e
    with:
      branch: ${{ github.event.inputs.branch || 'parallel_e2e' }}
      user: ${{ github.event.inputs.user || 'schedule' }}
      spec: ${{ github.event.inputs.spec || 'e2e/*' }}
      run-env: ${{ github.event.inputs.run-env || 'browsers:node16.18.0-chrome90-ff88' }}
      start-url: ${{ github.event.inputs.start-url || '' }}
      success-url: ${{ github.event.inputs.success-url || '' }}
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
