name: End-to-End tests parallel
run-name: Parallel E2E Tests ${{ inputs.branch }} - ${{ inputs.user }}

on:
  push:
    branches:
      - "parallel_e2e"
  repository_dispatch:
    types: [slack_command]
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub branch to test.'
        required: false
        default: 'parallel_e2e'
      user:
        description: 'User who kicked this off.'
        required: false
        default: 'schedule'
      spec:
        description: 'Specify specs.'
        required: false
        default: 'e2e/*'

jobs:
  e2e-node-14:
    name: base:14.21.1
    uses: n8n-io/n8n/.github/workflows/e2e-reusable.yml@parallel_e2e
    with:
      branch: ${{ github.event.inputs.branch || 'parallel_e2e' }}
      user: ${{ github.event.inputs.user || 'schedule' }}
      spec: ${{ github.event.inputs.spec || 'e2e/*' }}
      run-env: base:14.21.1'
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  e2e-node-16:
    name: base:16.18.1
    uses: n8n-io/n8n/.github/workflows/e2e-reusable.yml@parallel_e2e
    with:
      branch: ${{ github.event.inputs.branch || 'parallel_e2e' }}
      user: ${{ github.event.inputs.user || 'schedule' }}
      spec: ${{ github.event.inputs.spec || 'e2e/*' }}
      run-env: base:16.18.1'
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
